flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-0.11.3.0
- base-orphans-0.6
- bytestring-builder-0.10.8.1.0
- parsec-3.1.13.0
- semigroupoids-5
- slack-api-0.12
- websockets-0.11.1.0
- wuss-1.1.6
resolver: lts-5.14
